-- MySQL Script generated by MySQL Workbench
-- Tue Aug 11 21:48:06 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema db_blog
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_blog
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_blog` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `db_blog` ;

-- -----------------------------------------------------
-- Table `db_blog`.`post_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_blog`.`post_category` (
  `id` INT NOT NULL,
  `category_name` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `db_blog`.`posts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_blog`.`posts` (
  `post_id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) NULL DEFAULT NULL,
  `content` VARCHAR(3000) NULL DEFAULT NULL,
  `author_id` VARCHAR(255) NULL DEFAULT NULL,
  `published_at` VARCHAR(30) NULL DEFAULT NULL,
  `tag` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`post_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 31
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `db_blog`.`posts_content`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_blog`.`posts_content` (
  `post_id` INT NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `post_body` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`post_id`, `title`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `db_blog`.`tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_blog`.`tag` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tagName` VARCHAR(45) NOT NULL,
  `tagContent` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `tagName_UNIQUE` (`tagName` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 31
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `db_blog`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_blog`.`users` (
  `user_id` INT NOT NULL,
  `first_name` VARCHAR(30) NULL DEFAULT NULL,
  `last_name` VARCHAR(30) NULL DEFAULT NULL,
  `email` VARCHAR(30) NULL DEFAULT NULL,
  `password` VARCHAR(255) NULL DEFAULT NULL,
  `nickname` VARCHAR(30) NULL DEFAULT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
